site_name: Tech Blog
nav:
    - News: index.md
    - About: about.md
    - Go:        
        - Develop Env: go/go-develop-env.md
        - Grammar: go/go-grammar.md            
        - Features:
            - Go GC: go/go-gc.md
            - Go Build: go/go-build-linux-onWindows.md
        - Library:
            - Google API: go/go-google-api-usage.md
            - Apple Login Redirect Sever: go/apple-login-redirect.md
            - Gin Swagger: go/go-gin-swagger.md
            - Google Play Developer API: go/google-play-developer-api.md
            - Gin MongoDB: go/go-gin-mongodb.md
            - Gorilla WebSocket: go/go-gorilla-websocket.md
            - Gin CORS: go/gin-cors.md
    - iOS:
        - Grammar:
            - Swift: ios/ios-grammar.md
        - Features:
            - Swift ARC: ios/apple-arc.md
            - Framework Definition: ios/use_frameworks_definition.md
            - Exclude Architecture: ios/ios_exclude_simulator_architecture.md
        - Library:
            - AfNetworking: ios/afnetworking-usage.md
            - InAppPurchase: ios/ios-inapp-purchase-usage.md
            - Create Framework: ios/app-with-framework.md
            - Cocoapod Usage: ios/cocoapod-usage.md
            - Cocoapod Private: ios/cocoapods-private.md
            - Cocoapod Public: ios/cocoapods-public.md            
            - Apple Login: ios/apple-login.md
    - Android:
        - Grammar:
            - Kotlin: android/android-grammar.md
        - Features:
            - GC: android/android-gc.md
            - PackagenameRefactor: android/android-package-refactor.md
            - Proguard: android/android-proguard.md
        - Library:
            - ACRA: android/acra-usage.md
            - GoogleBilling: android/android-google-billing-usage.md
            - OneStoreBilling: android/android-onestore-billing-usage.md
            - Create Module: android/create-library.md
            - Create Only Module: android/only-library.md
            - Gson: android/gson.md
            - Retrofit2: android/retrofit2.md
            - AppleLogin: android/android-appleLogin.md
            - ServiceID Setting: ios/ios-serviceID-setting.md
        - Gradle:
            - Maven: android/maven-deploy.md
            - Jcenter: android/jcenter.md
    - Unity:
        - Grammar:
            - C#: unity/c#-grammar.md
            - API: unity/unity-api.md
        - Features:
            - Android Gradle: unity/gradle-version-manage.md
            - AndroidX Use: unity/unity2017-androidx-use.md
            - iOS Capability: unity/unity_xcode_AddInAppPurchase.md
            - iOS Application Override: unity/unity-ios-application-override.md
        - Library:
            - Asset: unity/unity-api.md
        - Editor:
            - Build Machine: unity/unity-build-machine-shell.md
    - DB:
        - Mysql/MariaDB: db/mysql.md
        - MongoDB: db/mongodb.md
        - Redis: db/redis.md
        - LevelDB: db/leveldb.md
    - Docker:
        - Build Deploy: docker/docker-build-deploy.md
        - Compose: docker/docker-compose.md    
    - Shell:
        - GPG Key: shell/gpg-usage.md
        - MAC Terminal: shell/mac-terminal.md
        - Linux Terminal: shell/linux-terminal.md
    - CI/CD:
        - Jenkins:
            - Jenkins Setup: ci/jenkins-setup.md
            - Jenkins SDK Build and Deploy: ci/jenkins-sdk-build-deploy.md
            - Python in Jenkins: ci/jenkins-python.md
            - Docker Build and Deploy in Jenkins: ci/jenkins-docker-build-deploy.md
        - Fastlane:
            - Fastlane Setup: ci/fastlane-setup.md
        - Travis: ci/travis-ci.md
    - Package Manager:
        - Homebrew: pm/homebrew.md
        - Cocoapod: pm/cocoapod.md
        - PIP: pm/pip.md
        - apt: pm/apt.md
        - yum: pm/yum.md
        - pnpm: pm/pnpm.md
        - PUB: pm/pub.md
theme: material
markdown_extensions:
    - admonition
    - toc:
        permalink: "#"